### ISSUE TITLE
Sugestão: Criar Estoques Virtuais durante a importação dos produtos

### ISSUE THREAD

**Issue by rafaelpatro** [integracommerce/modulo-magento#1]
É inviável manipular diferentes Estoques quando se tem muitos produtos. Por isso gostaria de sugerir a criação de Estoques no integracommerce através de um atributo no Magento.

Muitas lojas utilizam um atributo para definir o prazo de postagem (ou crossdocking) de cada produto. O módulo poderia permitir o mapeamento desse atributo.

Mas no caso da Magazine que não trabalha com crossdocking, mas com Estoques... nesse caso é interessante criar os Estoques automaticamente durante a importação dos produtos.

Exemplo:
O campo _crossdocking_ é mapeado para _prazo_postagem_ nas configurações do módulo.
O campo _Criar Estoque Virtual_ é ativado.
Ao enviar o produto para o integracommerce, verifica o campo _prazo_postagem_, e se necessário cria o Estoque Virtual (ex.: PRAZO_5), associando o produto ao novo estoque.
![image](https://user-images.githubusercontent.com/13813964/33637309-58be4858-da07-11e7-9b65-7432a2b6d51c.png)

**Comment by leonardo-novapc** [comment]
Olá Rafael, agradecemos o contato. Em breve teremos uma funcionalidade que atenderá esse cenário.
