### ISSUE TITLE
O módulo está registrando o campo base_grand_total incorretamente

### ISSUE THREAD

**Issue by rafaelpatro** [integracommerce/modulo-magento#2]
Bom dia, gostaria de reportar um problema que percebi desde que instalei o módulo.

Para cada tipo de totalizador o Magento armazena em 2 moedas. A moeda base, e a moeda da loja.

![image](https://user-images.githubusercontent.com/13813964/33880574-2f102d48-df19-11e7-9f3e-d3f154603004.png)

Dessa forma o Magento armazena cada total em 2 campos diferentes (ex.: _grand_total_ / _base_grand_total_).
Os pedidos do integracommerce exibem o _grand_total_ com o valor total do pedido (perfeito). Mas exibem o _base_grand_total_ com o valor dos produtos (sem frete), o que não faz sentido algum.

Como fica a tela dos pedidos:
![image](https://user-images.githubusercontent.com/13813964/33882075-1000b2c4-df1e-11e7-89ac-c32053f77722.png)

Enfim, estou apenas reportando o que percebi, mas isto não atrapalha o funcionamento do módulo, ou mesmo da loja.

**Comment by leonardo-novapc** [comment]
Olá Rafael, agradecemos o contato. Como é uma situação que não influenciará no funcionamento do módulo, realizaremos a alteração em uma atualização futura.
