### ISSUE TITLE
Sugestão: Diferentes Stores para diferentes Marketplaces

### ISSUE THREAD

**Issue by rafaelpatro** [integracommerce/modulo-magento#3]
Bom dia

Gostaria de sugerir a associação de diferentes stores no Magento, para cada marketplace no Integracommerce. O lojista teria um controle mais acurado dentro da plataforma.

Enfim, fica a sugestão. Uma boa semana.

**Comment by leonardo-novapc** [comment]
Boa tarde Rafael,

Não é possível esta associação devido ao controle de qual marketplace será enviado ser feito pelo Integracommerce.
