### ISSUE TITLE
Problema na atualização do módulo, da versão 2.0.1-2.0.3

### ISSUE THREAD

**Issue by az2009** [integracommerce/modulo-magento#4]
Caros, identifiquei uma falha no script de instalação mysql4-upgrade-2.0.1-2.0.3.php ao analisar o código abaixo:
$tablePrefix = Mage::getConfig()->getTablePrefix();
if (!empty($tablePrefix)) {
    $queueTable = $tablePrefix . 'npcintegra_product_queue';
    $attrTable = $tablePrefix . 'npcintegra_sku_attributes';
} else {
    $queueTable = 'npcintegra_order_queue';
    $attrTable = 'npcintegra_sku_attributes';
}

  Verifiquei que se a tabela tiver prefixo ele adiciona o unique product_id para a  tabela npcintegra_product_queue e quando não há prefixo adiciona para a tabela npcintegra_order_queue, analisando a tabela npcintegra_order_queue verifiquei que não existe a coluna product_id, acredito que seja um erro, uma vez que a coluna product_id esta na tabela npcintegra_product_queue e lá sim precisa ser único para não adicionar itens duplicados na sincronização da fila. Estou com um cliente relatando que informa que o suporte de vocês falam que com a atualização desta versão do módulo a fila não deveria ter itens duplicados mas esta duplicando acredito que seja devido  a isto.

**Comment by leonardo-novapc** [comment]
Boa tarde,
Agradecemos o feedback, o erro já foi corrigido.

**Comment by az2009** [comment]
em qual versão o erro foi corrigido pois ao ver o script mysql4-upgrade-2.0.4-2.0.5.php é quase um ctrl-c ctrl-v do script mysql4-upgrade-2.0.1-2.0.3.php

**Comment by az2009** [comment]
Vocês corrigiram no arquivo mas quem instalou o módulo e esta com uma versão mais atualizada, não esta com o unique na coluna product_id da tabela npcintegra_product_queue e consequentemente esta com os itens duplicando e tendo problema ao executar o update dos produtos na api de vocês que inclusive cada request demora mais de um minuto para atualizar um produto, impressionante a importância que vocês dão ao seus clientes. Taparam o Sol com a peneira os clientes estão lá com a tabela estourando de itens duplicados

**Comment by leonardo-novapc** [comment]
Boa tarde,

Está sendo analisado se algum cliente foi afetado, até o momento não foi identificado. Garantimos que os clientes não estão com a tabela estourando de itens duplicados.

**Comment by az2009** [comment]
A tenho sim,  quando é um grande case que tem um volume muito alto de pedido a tabela nunca é zerada devido a este problema de itens duplicados e também devido a demora da API de vocês, a tabela nunca é zerada. Pois o número de itens que entram é maior do que sai, pois a API demora um absurdo para integrar um item.
