### ISSUE TITLE
Problema grave de lógica

### ISSUE THREAD

**Issue by az2009** [integracommerce/modulo-magento#6]
Caros traduzindo o código abaixo vemos um erro grotesco, no if ele verifica se a coluna não existe caso ela não exista logo ele altera a coluna ***ops, buguei*** como assim se ela não existe eu altero ela.

if (!$installer->getConnection()->tableColumnExists($queueTable, 'product_id')) {
    $installer->run("ALTER TABLE `" . $queueTable . "` ADD UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC);");
}
if (!$installer->getConnection()->tableColumnExists($attrTable, 'category')) {
    $installer->run("ALTER TABLE `" . $attrTable . "` ADD UNIQUE INDEX `category_UNIQUE` (`category` ASC);");
}

**Comment by leonardo-novapc** [comment]
Boa tarde,

Por favor, verifique o arquivo mysql4-upgrade-2.0.4-2.0.5.php, ele contem a correção para este erro.
