### ISSUE TITLE
Problema criando pedido no website/store errada, não filtra o customer por website

### ISSUE THREAD

**Issue by az2009** [integracommerce/modulo-magento#7]
Caros ao analisar o módulo verificamos que ao pesquisar o cliente na loja não é realizado um filtro pelo website configurado mas apenas pelo taxvat, desta forma ele pesquisa se existe determinado cliente na loja sem importar em qual website o cliente esta cadastrado. Nas lojas que possuem cadastro de cliente separado por Website gera problemas.

Segue abaixo as evidências:

Classe: Novapc_Integracommerce_Helper_OrderData
Método: processingOrder
Trecho:
if (!empty($customerDoc)) {
$customerCollection = Mage::getModel('customer/customer')
->getCollection()
->addFieldToFilter('taxvat', $customerDoc)
->addAttributeToSelect('*')
->setPageSize(1)
->setCurPage(1);
foreach ($customerCollection as $customer) {
$customerId = $customer->getId();
}
}

Em nenhum momento é filtrado o customer pelo website configurado(Novapc_Integracommerce_Helper_Data::getStore()) para criar o pedido, com isso quando o cliente já existe na loja, o pedido é criado no website que o cliente foi registrado pela loja e não o que foi configurado no módulo. O comportamento normal era filtrar se o cliente já existe no website configurado senão cria-lo. Mesmo que ele exista em outro website na loja.

**Comment by az2009** [comment]
Boa tarde,

Na rotina de criação de cliente (app/code/local/Novapc/Integracommerce/Helper/OrderData.php, método createCustomer) é filtrado a loja selecionada nas configurações do módulo para a criação do cliente, ou seja, neste momento ele é criado na loja selecionada com seu devido CPF/CNPJ, o que nos próximos pedidos a filtragem pelo CPF/CNPJ já faz suficiente para encontrar o cliente no website correto.

 - Não juvenil, caso esse cliente já exista na loja antes de comprar pelo Marketplace, antes dele entrar na loja através da integracommerce, quando ele comprar pelo marketplace e ser integrado na loja vai ser carregado o primeiro cadastro que ele fez pela loja, porque na verificação que vocês fazem se o cliente já existe não filtra o marketplace configurado.

**Comment by leonardo-novapc** [comment]
Boa tarde,

Agradecemos o contato, iremos analisar o cenário citado e realizar a correção se necessário.

**Comment by az2009** [comment]
Solicitei meu cliente entrar em contato com vocês solicitando a correção
